# Generated by Django 2.2.10 on 2022-06-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_remove_resume_jobid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='mobile_number',
        ),
    ]
